name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: List build artifacts
        run: ls -R target || echo "Target folder not found"

  docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/ngbontsi/originaltaskmanager/originaltaskmanager:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/ngbontsi/originaltaskmanager/originaltaskmanager:latest

  deploy-demo:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Simulated deployment to AWS EC2 (demo)
        run: |
          echo "Simulating deployment..."
          echo "Pulling Docker image: ghcr.io/ngbontsi/originaltaskmanager/originaltaskmanager:latest"
          echo "Running container on EC2 (this is just a placeholder!)"
